version: "3.8"
services:
  mongodb-container:
    image: "mongo"
    volumes:
      - data:/data/db

  node-container:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb-container

  react-container:
    build: ./frontend
    ports:
      - "3000:3000"  
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - node-container

volumes:
  data:
  logs:

